### ISSUE TITLE
Refactor the menu

### ISSUE THREAD

**Issue by Stansbridge** [Stansbridge/tangled#1]
- Remove the 'pause menu'
- Rework all menu code

* https://github.com/neontribe/untangled-2017/blob/master/screen.py#L111
We want to simplify the API for the offset calculation

`MenuList.add('Foobar')`
`MenuList.update(pygame.stuff)`

* https://github.com/neontribe/untangled-2017/blob/master/screen.py#L139
We want to avoid handling input again

**Comment by whizzer0** [comment]
Done in #4
